#!/usr/bin/env sh
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="Hack Nerd Font"
# FONT="SF Pro"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  position=top
  height=25
  margin=0
  corner_radius=0
  color=$BAR_COLOR
  shadow=off
  sticky=on
  padding_left=8
  padding_right=8
  y_offset=0
)
sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=8
  padding_right=8
  icon.padding_left=6
  icon.padding_right=6
  label.padding_left=6
  label.padding_right=6
  icon.font="SF Pro:Semibold:16.0"
  label.font="SF Pro:Medium:13.0"
  icon.color=$ICON_COLOR
  label.color=$LABEL_COLOR
  background.height=20
  background.corner_radius=4
  background.padding_left=2
  background.padding_right=2
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

##### Adding Center Items #####
# Media player widget in the center

source "$ITEM_DIR/media.sh"

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/network.sh"
source "$ITEM_DIR/memory.sh"
source "$ITEM_DIR/cpu.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
