return {
  -- {
  --   "neovim/nvim-lspconfig",
  --   name = "lspconfig",
  --   dependencies = {},
  --   -- event = { "LazyFile" },
  --   -- TODO: add more language LSP config
  --   opts = {
  --     -- you can do any additional lsp server setup here
  --     -- return true if you don't want this server to be setup with lspconfig
  --     setup = {
  --       -- rust_analyser = function(_, opts)
  --       --   require("lspconfig").rust_analyser.setup({
  --       --     server = opts,
  --       --     root_dir = require("lspconfig").util.root_pattern("Cargo.toml"),
  --       --   })
  --       -- end,
  --       -- Specify * to use this function as a fallback for any server
  --       -- ["*"] = function(server, opts) end,
  --     },
  --   },
  -- },
}
